<?xml version="1.0" encoding="utf-8"?>
<!--IT'SNOT COMPLETELY RIGHT. IT'S A GENERAL IDEA OF HOW IT SHOULD LOOK LIKE. -->
<definitions
        targetNamespace="http://www.kth.se/ict/id2208/Matching/getDrink.wsdl"
        xmlns:tns="http://www.kth.se/ict/id2208/Matching/getDrink.wsdl"    
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        
        xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"  >

<types>
  <!--data type definitions........ -->
  <schema targetNamespace="http://www.kth.se/ict/id2208/Matching/getDrink.xsd"
          xmlns="http://www.w3.org/2000/10/XMLSchema">                           
            <element name="Drink">
               <complexType>
                   <all>
                     <element name="Country" type="string"/>
                     <element name="Cost" type="float"/>
                     <element name="Area" type="string"/>
                     <element name="Colour" type="string"/>
                   </all>
               </complexType>
            </element>
    </schema>
</types>


<!--definition of the data being communicated.... THE FOLLOWING ELEMENTS/NAMES ARE NOT CORRECT YET-->
<wsdl:message name="GetDrinkInput">
        <wsdl:part name="parameters" element="tns:Request"/> 
</wsdl:message>
<wsdl:message name="GetDrinkOutput">
        <wsdl:part name="parameters" element="tns:Response"/> 
</wsdl:message>


<!--set of operations......-->
<portType name="DrinkPort">
    <operation name="Drink">
       <input message="tns:GetDrinkInput"/>
       <output message="tns:GetDrinkOutput"/>
    </operation>
</portType>


<!--protocol and data format specification....-->
<binding name="DrinkBinding" type="tns:DrinkPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetDrink">
           <soap:operation soapAction=""/>
           <input>
               <soap:body use="literal"/>
           </input>
           <output>
               <soap:body use="literal"/>
           </output>
        </operation>
</binding>

<service name="DrinkService">
        <documentation>Drink service</documentation>
        <port name="DrinkPort" binding="tns:DrinkBinding">
           <soap:address location="http://www.kth.se/ict/id2208/Matching"/>
        </port>
</service>

</definitions>